-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguVWFerlp13Q+hmJ2
KrK64FRt0NHTPPEFFVOSKRH+4BGgCgYIKoZIzj0DAQehRANCAARQvLDVZFG+ppMO
19B8/7LKmpRlnmjQAGnKXXq/PtJTnRKgU1KOM/4hwLkr5U1IGZF+Sa7Dt5uocaw4
HLtuwK09
-----END PRIVATE KEY-----