-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDJuhKpV0fMu8YDte
pykkeV8NGsXfWjL04I6h1l/UbCCgCgYIKoZIzj0DAQehRANCAATKw+oU6bfahHnL
vM1/ocN5vAajfetaFvunmcMQmNFpgnS7wWaj9GiyYxX6HmyU+RSrtpBDd5JWo0M4
Hbcktc//
-----END PRIVATE KEY-----