-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgR+dJ8aZZMRggnWgG
DJgYTB4l0nBABl21mBYuGNt8IamgCgYIKoZIzj0DAQehRANCAASakCkiq1r0Gkm5
JNvWpAOX/EZb68T7+N6BWLAAf+jysCex6rX2dbfGiUBhytSKX2FOLnWDpg8u9o+C
YwLyl7/J
-----END PRIVATE KEY-----