-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLzJnfxnbETHPsWXI
m+qzkuluvSfhXQMRwsn0+Jtv73GgCgYIKoZIzj0DAQehRANCAATHMeIjx2Q2gCKe
BHJz4eOIJNocYoCZu3/prT/1+08lkK7obKIxoeG+gHd6iaDomG0PUQrtUaAQ2DME
YsX212w9
-----END PRIVATE KEY-----