-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglRSIHDes4NJLAeNw
Gh298MP1NtRv3vZ+7lNNHDUURPygCgYIKoZIzj0DAQehRANCAATfabqdfCLUdPHd
cp9zMIqxzve5kzLCjZcjCQJrvktKhLXDStE+TFZ3T0Mu6odasTZdjn6LLtZ0C0+n
CUCw+9vX
-----END PRIVATE KEY-----