-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkGRwsgIbOmn+oN92
vPxY90HyrdWHkveR8ezIsuxzJX6gCgYIKoZIzj0DAQehRANCAAREaOLTX2SdLIEI
EDKKB6+I0XFgyInbu7LpDZg8ge/9OSsW4x52cxBtKprl6OUXMeQZIdRHyZjTCEs9
QxD39hdl
-----END PRIVATE KEY-----