-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOpcXUy4ofKBccXpM
MnMeXK1KYLByxj4EyWNIYKO/TiGgCgYIKoZIzj0DAQehRANCAATOXFvLuQlq4M9r
HpaoF7sSllSREKqBr20x9VtdEBQKw8ag2kc3IOKnh6wAW4E+NBuXxNrzIHdaftR8
aMJMe6E6
-----END PRIVATE KEY-----