-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLiiKx6WnM0udU2A+
FaUn+yRlHGaYuI0Q/d74WMsbXFigCgYIKoZIzj0DAQehRANCAATbtOW4fRuQWqyW
tP/hHlo9fbQ/F90pf3WNJQtbG8r7nd6uFu4BgWzLc+WFwLOuW9LQBbFNnCoV1SpY
ybWAduLO
-----END PRIVATE KEY-----