-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfZuggUhTzndwEzbF
DMOPiRF4yzdoLWXTMsKU2YWNaTugCgYIKoZIzj0DAQehRANCAAQNG/4xLbzvC03w
92lmzFbCJdAsPiXKLj3zy1cGN4yKH98Ei4PXun7NpfBvmMxb0RM/Zy5lMw1VMyx2
BDRFy9lH
-----END PRIVATE KEY-----