-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUdRXCrNEbcudkbnL
YlnWMTHPMQP9VY8SUEkMXAHG9ymgCgYIKoZIzj0DAQehRANCAASdxn5sI3WSRSTl
nD/NQTBk9OXJFwCZs/zvDNUbwoyJZ3p9EGUJ0m0adumKFfNDnICqD8JzS2olxdrJ
jnctvn89
-----END PRIVATE KEY-----