-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyqqeRpPsWDg7IDu/
GYWNYHgplqpOw5MrPg+UaIfm+nugCgYIKoZIzj0DAQehRANCAAQLAkDPXCZ/ZXbd
8ddltvANGQcNm7WbyYMhva2I9l9yaK5qpNVmxEwVDcVGvbsXwMoTWxP77Wg+XPY+
YM5WAEWR
-----END PRIVATE KEY-----