-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3CwOzrmraBN2bjZ1
VqXCTu3vXYxiJCRmgMUWBnT8WuagCgYIKoZIzj0DAQehRANCAATObEM7jbrZNY5+
UKQ61gOvsibZnGGHpVrtXaleKfqGRwEyPQghVTeo/9hCffjAS685U8+1XbOX0orN
kRXuLDjk
-----END PRIVATE KEY-----