-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgM8a1JdZfIcSUYuPj
iGkwjziElFwaBstUSas1TZlCqN6gCgYIKoZIzj0DAQehRANCAAQNu/ng1DfLPqlQ
OqNAULEMfDwB4ZUhziOTgDwhc8sGfCWHS8J1uUHxHeHTc46Wyj/k/BeIcYDZO4Wv
EMLqhxmO
-----END PRIVATE KEY-----