-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgD88NcSWzGZGpRlDS
Y9mRtEYLz5p1aWOqzwHe49ec89ugCgYIKoZIzj0DAQehRANCAAQe9ptcD7hBPnCC
zrK4n/jhnJnLIfs10UODvv2N/aMsTIpXKzFcZjzR73j+D+Ye/pqNiRFetIaPQH9B
NuKTN6Ox
-----END PRIVATE KEY-----