-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKdxxxpzDrR0BLzoW
ZbucIl/m3v3tRy1mSbJAm9SYfuygCgYIKoZIzj0DAQehRANCAAQhIii/1ICx2apU
eCd5fVYvbij9tejJyGugoaoznyswmCCImV9H+H1N5h/atX05QxkVRrkVPC0XWe9/
0JUhLP8X
-----END PRIVATE KEY-----