# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'OverseaH5' do
  use_frameworks!

  pod 'Adjust', '~> 4.31.0'
  pod 'Firebase/Messaging', '~> 10.24.0'
  pod 'KeychainSwift', '~> 24.0.0'
  pod 'Alamofire', '~> 5.9.1'
  pod 'Firebase/RemoteConfig'
  
end

