# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'OverseaH5' do
  use_frameworks!
 
 pod 'WebViewJavascriptBridge', :git => 'https://github.com/stury/WebViewJavascriptBridge.git', :branch => ‘master’
  pod 'Adjust', '~> 4.31.0'
  pod 'Firebase/Messaging', '~> 10.24.0'
  pod 'KeychainSwift', '~> 24.0.0'
  pod 'Alamofire', '~> 5.9.1'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'Firebase/RemoteConfig'
  
end

# 统一的 post_install 处理
post_install do |installer|
  # HandyJSON 优化设置 - 解决编译问题
  installer.pods_project.targets.each do |target|
    if target.name == 'HandyJSON'
      target.build_configurations.each do |config|
        # Apple Clang - Code Generation: Optimization Level 设置为 None [-O0]
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        # Swift Compiler - Code Generation: Optimization Level 设置为 No Optimization [-Onone]
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end

