-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4CK0317hphqBF0f/
7zMTXlDdL9NABM/jBIP24VZQSTWgCgYIKoZIzj0DAQehRANCAATMzJN+YtppJjGz
fCTidcT+sTgMWrhFmyQnmv3Foh3O33oBvKVYahfZWJP+pqZEQ3OefZGXkT7SOs8K
pIfMeKh/
-----END PRIVATE KEY-----