-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXdTVqSbAxu90msD8
CnG/Yfhsr7VKuMPaVfDNiiHFTkegCgYIKoZIzj0DAQehRANCAASfcIUESsFHu/Z+
JtgQh8CRTIdYjfh3hsNjtXgb+9FIUCx88ZCQFOMLVPD0fFsaxgndPOogYBglracw
KJ3trXqz
-----END PRIVATE KEY-----