-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXzx9U6G4B6Rz1hB1
nEv3rzXhdLPJfmsdPRfbcfvOtrOgCgYIKoZIzj0DAQehRANCAAQ0uvsoQFuxA9LH
pJzEdSlqdjV+4prflYBrrFJ+kWingDdHI0nJIC1xhU8fuNKfUKxBd/lw3knr3llj
QyomhzQN
-----END PRIVATE KEY-----