-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiOBRS7wLtjr9G3cJ
Ad3bDuneoVpZWrRYpvZNC1r2r4mgCgYIKoZIzj0DAQehRANCAATHMzBSDGkStCqd
Xsbw0QVpznt2xP3KVwhxjkFU4g7BFBPQmlrb3s0cVqADRAxOq5hN4dl7PZU5ub08
BsFgfYmi
-----END PRIVATE KEY-----