-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkMPaNPqf2+APyJQ6
jp7svF4UAfqtCNzt1Op9WlnCRnqgCgYIKoZIzj0DAQehRANCAAQrsXXPDVeoSQ61
68EKTjTuIgldC4+71zzRYwGbQrJeAFLjz0JBERjr/d7/yFuXAbJx2CDXCavE8AVQ
FoYlN9eT
-----END PRIVATE KEY-----