-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggI2gHwM0DIWaw1AK
BNh6scHy0ZMGJ+zbjMBvJaVcKQGgCgYIKoZIzj0DAQehRANCAAQ9Vq0//Rr/mlid
L8PEVtGwGg/tAA2odVKhJWzMnToP7Ym7r4/h6E3HaaoxPy9Vbax0dLigIQQ1A8Tu
/qR9pxYk
-----END PRIVATE KEY-----