# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'sunni' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'WebViewJavascriptBridge', :git => 'https://github.com/stury/WebViewJavascriptBridge.git', :branch => 'master'
  pod 'Adjust', '~> 4.31.0'
  pod 'Firebase/Messaging', '~> 10.24.0'
  pod 'KeychainSwift', '~> 24.0.0'
  pod 'Alamofire', '~> 5.9.1'
  pod 'HandyJSON', '~> 5.0.2'
  pod 'Firebase/RemoteConfig'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    if target.name == 'HandyJSON'
      target.build_configurations.each do |config|
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
