-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbZ0gRXvGtZEvBzVl
IZG5/vmV6GlTnqpQZHIXpQRRi6GgCgYIKoZIzj0DAQehRANCAASC4WuUroBeJ+CZ
9dQdnHbo7V434hb1bmVxFjRdcgjwAknwybo8z2TQtQX8YCbUdGPv3p38t14Igyfg
ObWdom2J
-----END PRIVATE KEY-----