-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHo4MpYFNnYtD6r0D
WejP4KvJDrA05YtqSL6bJGsgVBugCgYIKoZIzj0DAQehRANCAASgQIpRKLYNM71R
xhSpXdtEWiP4Tb/B/dYxeNMmoG5RbWNEHJl7uRfa0pcLO9aKi2QTW1frZ9yRfMyB
Z9myx2jS
-----END PRIVATE KEY-----